"""Initial tables

Revision ID: e93fe883f0dd
Revises: 
Create Date: 2026-03-08 20:11:44.415626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93fe883f0dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sessions', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('device_sessions', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('device_sessions', 'refresh_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_sessions', 'refresh_token_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('device_sessions', 'location')
    op.drop_column('device_sessions', 'ip_address')
    # ### end Alembic commands ###
